# Generated by Django 4.1.5 on 2023-01-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monuments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monument',
            name='description',
            field=models.TextField(),
        ),
    ]
