# Generated by Django 4.1.5 on 2023-05-29 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('object_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='historical_objects.objecttypes')),
            ],
        ),
    ]
