# Generated by Django 4.1.5 on 2023-07-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historical_objects', '0002_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='mail',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
