# Generated by Django 4.1.5 on 2024-01-10 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('historical_objects', '0003_alter_mail_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryHistoricalObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('object_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='historical_objects.objecttypes')),
            ],
        ),
        migrations.CreateModel(
            name='ProposedHistoricalObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('object_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='historical_objects.objecttypes')),
            ],
        ),
    ]
