# Generated by Django 4.1.5 on 2024-02-21 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='object_type',
            new_name='profile',
        ),
    ]
