# Generated by Django 4.1.5 on 2024-02-21 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('historical_objects', '0006_proposedhistoricalobject_author'),
        ('user_profiles', '0002_rename_object_type_comment_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='hist_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='historical_objects.historicalobject'),
        ),
    ]
