# Generated by Django 4.1.5 on 2023-02-06 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Custom',
            new_name='Culture',
        ),
    ]
